### ISSUE TITLE
Is the Nginx patch relevant for recent Nginx?

### ISSUE THREAD

**Issue by petecooper** [zlib-ng/patches#2]
https://github.com/zlib-ng/patches/blob/master/nginx/1.18.0-zlib-ng.patch
http://mailman.nginx.org/pipermail/nginx-devel/2021-April/013945.html
https://hg.nginx.org/nginx/rev/1f3d0d9f893f

Hello. Firstly, thank you for all your work on `zlib-ng`, I am looking forward to using it!

My question relates to the validity of the above patch for Nginx. I understand it is intended for Nginx 1.18.0, and the patch pre-dates Nginx adding support for `zlib-ng` (see other link above).

Are there any further changes or patches to be applied to enable Nginx to use `zlib-ng` in its current guise (i.e. Nginx with support for `zlib-ng`)?

Thank you.

**Comment by Dead2** [comment]
Interesting that nginx supports zlib-ng, but only in compat mode.
Our patch is still required to support zlib-ngs native API, some changes might be required due to their changes, until we have an updated patch here it might be easiest to revert their patch before applying ours.

**Comment by eilandert** [comment]
Any change on an updated patch soon? ;-)

**Comment by kleisauke** [comment]
FWIW, nginx just updated its implementation to ensure compatibility with recent zlib-ng versions. See:
http://hg.nginx.org/nginx/rev/fcb2333c9982

**Comment by Dead2** [comment]
> FWIW, nginx just updated its implementation to ensure compatibility with recent zlib-ng versions. See: http://hg.nginx.org/nginx/rev/fcb2333c9982

That fixes zlib-ng support when zlib-ng is compiled in Zlib-compat mode. The patch in this repo however adds support for compiling nginx with zlib-ng using its native API, this also allows using zlib-ng on a distro that normally uses zlib. Hopefully Nginx will add proper support for the native api soon, as that is our recommended API and it is now available on several distros.

Btw, the patch in this repo applies cleanly to Nginx 1.22, but likely has some minor conflicts with the current development release because of that change.

**Comment by eilandert** [comment]
I rebased the patch.   PR #4

**Comment by mtl1979** [comment]
> Interesting that nginx supports zlib-ng, but only in compat mode.

As I see it, nginx needs further abstraction to be able to switch between zlib and zlib-ng. Current patches can never be merged verbatim in upstream due to essentially removing support for stock zlib in favor of supporting zlib-ng. Configure system of nginx essentially has to have a switch to disable looking for zlib and linking against it, if zlib-ng without compatibility mode is requested.
