### ISSUE TITLE
How does the nginx patch work?

### ISSUE THREAD

**Issue by zingaburga** [zlib-ng/patches#5]
Sorry for my ignorance, but I've been trying to apply the 1.25.3 patch to nginx 1.26.2, however it doesn't seem to be using zlib-ng.

From what I can tell, the patch adds a bunch of checks for `NGX_ZLIB_NG`, but I can't find that actually being defined anywhere, so it always falls back to regular zlib.

If I add to *objs/ngx_auto_config.h*:

	#ifndef NGX_ZLIB_NG
	#define NGX_ZLIB_NG 1
	#endif

...then it seems to be try to use zlib-ng.  
(I'm guessing this file is auto-generated, so the above change won't work in a patch)

After that, on 1.26.2, this leads to the following build errors:

	src/http/modules/ngx_http_gunzip_filter_module.c: In function ‘ngx_http_gunzip_filter_inflate’:
	src/http/modules/ngx_http_gunzip_filter_module.c:464:26: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
	  464 |         ctx->in_buf->pos = ctx->zstream.next_in;
		  |                          ^
	src/http/modules/ngx_http_gzip_filter_module.c: In function ‘ngx_http_gzip_filter_deflate’:
	src/http/modules/ngx_http_gzip_filter_module.c:785:26: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
	  785 |         ctx->in_buf->pos = ctx->zstream.next_in;
		  |                          ^
	cc1: all warnings being treated as errors

If I replace both instances of `ctx->in_buf->pos = ctx->zstream.next_in;` with `ctx->in_buf->pos = (u_char*)ctx->zstream.next_in;` the build succeeds.

I haven't tested this build, but from what I can tell, the patch here doesn't address nginx's "failed to use preallocated memory" errors.  I'm guessing you consider this to be more of an issue on their side, instead of this patch?  Regardless, I've [filed an issue](https://github.com/nginx/nginx/issues/263) there.

**Comment by mtl1979** [comment]
zlib-ng 2.2 isn't supposed to be used with anything that isn't specifically designed to be used with zlib-ng. zlib-ng 2.1 is last version that will support applications and libraries that are not updated for zlib-ng's own API.

Eventually when most of Linux distributions have switched from zlib to zlib-ng, we will remove the compatibility mode and only zlib-ng's own API can be used. It is up to maintainers of the distribution(s) to decide if they want to treat zlib-ng 2.2 and later versions as separate package from older versions or not, as clearly there is break in backwards compatibility.

**Comment by Dead2** [comment]
@mtl1979 I don't know where you have that from, but zlib-ng 2.2 is perfectly capable of running in zlib compat mode.

The problem here is not zlib/zlib-ng, it is that Nginx assumes that zlib/zlib-ng allocates a set number of bytes total and no more. That number needs to be updated in Nginx so that it pre-allocates the correct number of bytes, or better yet, lets us do the allocation ourselves. Zlib never promised to use a fixed size memory allocation, so Nginx breaks (gives runtime warnings) whenever zlib does changes as well.

@zingaburga I am going to release an updated patch soon, just dealing with some sickness that is slowing me down.
I don't know why you compile with -Werror though, on my system Nginx does not enable -Werror.
And yes, you need to add -DNGX_ZLIB_NG to CFLAGS for the build. I guess that could be hardcoded in instead.

**Comment by mtl1979** [comment]
> @mtl1979 I don't know where you have that from, but zlib-ng 2.2 is perfectly capable of running in zlib compat mode.

Zlib was written when people were still using 16-bit computers, There was no vector instructions or anything that would warrant any special handling (including enforcing alignment)... What nginx does is not wrong, it's still in grey area due to a lot of things in zlib being undefined but still predictable. Compatibility layer in zlib-ng is not 100% accurate and nobody has even promised it to be.

I completely agree that a new patch should (read: need to) be made, as we can expect people to try compiling nginx against the latest zlib-ng version.

BTW. Removing constness from pointers is generally bad idea as it allows writing to memory locations that are supposed to be read-only.

**Comment by Dead2** [comment]
The const warnings come from Nginx, not zlib-ng or the patch.
This should also fail with zlib as well, since next_in is const there as well. BUT, zlib needs to be compiled with `ZLIB_CONST` set for that to be enabled, and probably nobody knows about it so it is not enabled in most/any distros. Zlib-NG however assumes that people have new enough compilers to support const, so we always enable it in the native mode.
In any case, this is probably something Nginx should fix.

@zingaburga A new patch has been uploaded, based on 1.26.2. Also documented the necessary workaround in the readme.
You should probably update, since the old patch uses the wrong allocation size and Nginx will then print a warning for every http access, as well as having to do the allocations twice.

**Comment by zingaburga** [comment]
Thanks a lot for the responses and updated patch!

This seems to eliminate the gzip warnings in the log.

**Comment by eilandert** [comment]
just to be sure, is this patch compatible with both zlib-ng versions?

**Comment by Dead2** [comment]
@eilandert Yes, the newest patch should work for all zlib-ng versions.
It is allocating a bit more memory than is really needed for older versions due to changes in 2.2, but other than that there should be no dirrerences.
